version: '2'

services:

  idm-db:
    image: postgres:10.4-alpine
    environment: 
       POSTGRES_USER: keycloak
       POSTGRES_PASSWORD: keycloak
       POSTGRES_DB: idm_keycloak_demo
    ports:
      - "55432:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  idm-keycloak:
    build: ./keycloak
    environment: 
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      JDBC_URL: jdbc:postgresql://idm-db/idm_keycloak_demo
      JDBC_USER: keycloak
      JDBC_PASSWORD: keycloak
      JDBC_DRIVERNAME: postgres
    ports:
      - "8899:8080"
    extra_hosts:
      - "apps.tdlabs.local:172.18.0.1"
    depends_on:
      - idm-db
    volumes:
      - ./acme-realm.json:/opt/jboss/keycloak/acme-realm.json
      
